import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("healthz", "routes/healthz.ts"),
  route("signup", "routes/signup.tsx"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.ts"),
  route("invite/:token", "routes/invite.$token.tsx"),
  route("orgs/new", "routes/orgs.new.tsx"),
  route("orgs/:slug", "routes/orgs.$slug.tsx", [
    index("routes/orgs.$slug._index.tsx"),
    route("members", "routes/orgs.$slug.members.tsx"),
    route("tokens", "routes/orgs.$slug.tokens.tsx"),
    route("connect", "routes/orgs.$slug.connect.tsx"),
    route("drive", "routes/orgs.$slug.drive.tsx"),
    route("reports", "routes/orgs.$slug.reports.tsx"),
    route("requests/:id", "routes/orgs.$slug.requests.$id.tsx"),
    route("approvals", "routes/orgs.$slug.approvals.tsx"),
    route("approvals/:id", "routes/orgs.$slug.approvals.$id.tsx"),
  ]),
  route("github/setup", "routes/github.setup.ts"),
  route("mcp", "routes/mcp.ts"),
  route(".well-known/oauth-authorization-server/*", "routes/oauth.as-metadata.ts"),
  route(".well-known/oauth-protected-resource/*", "routes/oauth.prm.ts"),
  route("oauth/register", "routes/oauth.register.ts"),
  route("oauth/token", "routes/oauth.token.ts"),
  route("oauth/revoke", "routes/oauth.revoke.ts"),
  route("oauth/authorize", "routes/oauth.authorize.tsx"),
] satisfies RouteConfig;
