// MANIFEST.md: generated on every merge (RFC §2, §5). Agents read it first (RFC §6). Pure.
import { splitFrontmatter, titleFromPath, titleOf } from "./frontmatter";
import { parseEntryPath } from "./paths";
import { ENTRY_TYPES, FrontmatterSchema, TYPE_DIR, type EntryType } from "./schema";

export interface ManifestEntry {
  path: string;
  type: EntryType;
  domain: string;
  title: string;
  author: string;
  created: string;
  review_by: string;
  approved_by: string | null;
  archived: boolean;
}

export function entriesFromFiles(files: Array<{ path: string; raw: string }>): { entries: ManifestEntry[]; skipped: Array<{ path: string; reason: string }> } {
  const entries: ManifestEntry[] = [];
  const skipped: Array<{ path: string; reason: string }> = [];
  for (const f of files) {
    const pp = parseEntryPath(f.path);
    if (!pp) continue;
    const split = splitFrontmatter(f.raw);
    if (!split.data) {
      skipped.push({ path: f.path, reason: split.error ?? "no frontmatter" });
      continue;
    }
    const parsed = FrontmatterSchema.safeParse(split.data);
    if (!parsed.success) {
      skipped.push({ path: f.path, reason: "frontmatter does not match schema" });
      continue;
    }
    const fm = parsed.data;
    entries.push({
      path: f.path,
      type: fm.type,
      domain: fm.domain,
      title: titleOf(split.body) ?? titleFromPath(f.path),
      author: fm.author,
      created: fm.created,
      review_by: fm.review_by,
      approved_by: fm.approved_by,
      archived: pp.archived,
    });
  }
  entries.sort((a, b) => a.path.localeCompare(b.path));
  return { entries, skipped };
}

const cell = (s: string | null) => (s ?? "").replace(/\|/g, "\\|").replace(/\r?\n/g, " ");

export function renderManifest(entries: ManifestEntry[], generatedAt: string, skipped: Array<{ path: string; reason: string }> = []): string {
  const lines: string[] = [];
  lines.push("# MANIFEST");
  lines.push("");
  lines.push(`Generated by reedright at ${generatedAt}. Do not edit by hand. Read this file first, then read entries by path.`);
  lines.push("");
  for (const type of ENTRY_TYPES) {
    const rows = entries.filter((e) => e.type === type && !e.archived);
    lines.push(`## ${TYPE_DIR[type]} (${rows.length})`);
    lines.push("");
    if (rows.length) {
      lines.push("| path | domain | title | author | created | review_by | approved_by |");
      lines.push("| --- | --- | --- | --- | --- | --- | --- |");
      for (const r of rows) lines.push(`| ${cell(r.path)} | ${cell(r.domain)} | ${cell(r.title)} | ${cell(r.author)} | ${r.created} | ${r.review_by} | ${cell(r.approved_by) || "null"} |`);
      lines.push("");
    }
  }
  const archived = entries.filter((e) => e.archived);
  lines.push(`## archive (${archived.length})`);
  lines.push("");
  if (archived.length) {
    lines.push("| path | title |");
    lines.push("| --- | --- |");
    for (const r of archived) lines.push(`| ${cell(r.path)} | ${cell(r.title)} |`);
    lines.push("");
  }
  if (skipped.length) {
    lines.push("## skipped (invalid frontmatter)");
    lines.push("");
    for (const s of skipped) lines.push(`- ${s.path}: ${s.reason}`);
    lines.push("");
  }
  return lines.join("\n");
}

/** Parse a rendered MANIFEST back into entries (used by brain_list / brain_search). */
export function parseManifest(md: string): ManifestEntry[] {
  const out: ManifestEntry[] = [];
  let section: string | null = null;
  for (const line of md.split(/\r?\n/)) {
    const h = /^## (\w+)/.exec(line);
    if (h) {
      section = h[1];
      continue;
    }
    if (!line.startsWith("| ") || line.startsWith("| path") || line.startsWith("| ---")) continue;
    const cells = line.slice(1, -1).split(/(?<!\\)\|/).map((c) => c.trim().replace(/\\\|/g, "|"));
    if (section === "archive") {
      const pp = parseEntryPath(cells[0]);
      if (pp) out.push({ path: cells[0], type: pp.type, domain: pp.domain, title: cells[1] ?? "", author: "", created: "", review_by: "", approved_by: null, archived: true });
      continue;
    }
    if (cells.length < 7) continue;
    const pp = parseEntryPath(cells[0]);
    if (!pp) continue;
    out.push({ path: cells[0], type: pp.type, domain: cells[1], title: cells[2], author: cells[3], created: cells[4], review_by: cells[5], approved_by: cells[6] === "null" ? null : cells[6], archived: false });
  }
  return out;
}
