// Rules orchestration: toggle a rule for an org, keep the workflow in the brain repository in step with what is on,
// and read back what the workflow found on a pull request.
import type { Org } from "../../../generated/prisma/client";
import { prisma } from "../db.server";
import { BrainRepo } from "../github/repo.server";
import { RULES_WORKFLOW_PATH, checkName, parseEnabledRules, renderRulesWorkflow, ruleById, serializeEnabledRules, type RuleDef, type RuleHit } from "./rules";

const status = (e: unknown) => (e as { status?: number })?.status;

export type WorkflowChange = "written" | "removed" | "unchanged";

export interface RuleToggleResult {
  rule: RuleDef;
  enabled: boolean;
  rules: RuleDef[];
  workflow: WorkflowChange;
}

/** Turn a rule on or off. The workflow is committed first, so a refused commit leaves the setting as it was. */
export async function setRuleEnabled(org: Org, ruleId: string, enabled: boolean): Promise<RuleToggleResult> {
  const rule = ruleById(ruleId);
  if (!rule) throw new Error(`Unknown rule "${ruleId}".`);
  const current = parseEnabledRules(org.enabledRules);
  const next = parseEnabledRules(serializeEnabledRules(enabled ? [...current, rule] : current.filter((r) => r.id !== rule.id)));
  const workflow = await syncRulesWorkflow(org, next);
  await prisma().org.update({ where: { id: org.id }, data: { enabledRules: serializeEnabledRules(next) } });
  return { rule, enabled, rules: next, workflow };
}

/** Commit the workflow for these rules to the default branch, or delete it when there are none. */
export async function syncRulesWorkflow(org: Org, rules: RuleDef[]): Promise<WorkflowChange> {
  const repo = await BrainRepo.forOrg(org);
  if (!(await repo.headSha())) throw new Error("The brain repository is empty; scaffold it first.");
  const existing = await repo.readFile(RULES_WORKFLOW_PATH);
  const guarded = async (fn: () => Promise<unknown>) => {
    try {
      await fn();
    } catch (e) {
      if (status(e) === 422 || status(e) === 403) {
        throw new Error(`GitHub refused the workflow file (${(e as Error).message}). The reedright GitHub App needs the "Workflows: read and write" permission: add it to the app, then accept the permission update on this installation.`);
      }
      throw e;
    }
  };
  if (!rules.length) {
    if (!existing) return "unchanged";
    await guarded(() => repo.commit({ branch: repo.defaultBranch, message: "rules: none enabled; remove the workflow\n\nGenerated by reedright.", writes: [], deletes: [RULES_WORKFLOW_PATH] }));
    return "removed";
  }
  const content = renderRulesWorkflow({ defaultBranch: repo.defaultBranch, rules });
  if (existing?.content === content) return "unchanged";
  await guarded(() =>
    repo.commit({
      branch: repo.defaultBranch,
      message: `rules: ${rules.map((r) => r.name).join(", ")}\n\nGenerated by reedright. Each rule runs as a job on every pull request.`,
      writes: [{ path: RULES_WORKFLOW_PATH, content }],
    }),
  );
  return "written";
}

export type RuleCheckState = "not-run" | "pending" | "clear" | "flagged" | "inconclusive";

export interface RuleCheck {
  rule: string;
  name: string;
  state: RuleCheckState;
  /** The job on GitHub, when it ran. */
  url: string | null;
  /** GitHub's conclusion when it was neither success nor failure (cancelled, skipped, …). */
  conclusion: string | null;
  /** From the job's annotations, when it flagged something. */
  hits: RuleHit[];
}

export interface RuleChecks {
  checks: RuleCheck[];
  error: string | null;
}

/** What each enabled rule's job found on a commit, from the check runs GitHub Actions created for it. */
export async function readRuleChecks(repo: BrainRepo, headSha: string, rules: RuleDef[]): Promise<RuleChecks> {
  if (!rules.length) return { checks: [], error: null };
  const blank = (r: RuleDef): RuleCheck => ({ rule: r.id, name: r.name, state: "not-run", url: null, conclusion: null, hits: [] });
  let runs;
  try {
    runs = await repo.listCheckRuns(headSha);
  } catch (e) {
    const error = status(e) === 403 ? 'Rule results could not be read: the reedright GitHub App needs the "Checks: read-only" permission. Add it to the app, then accept the permission update on this installation.' : `Rule results could not be read: ${(e as Error).message}`;
    return { checks: rules.map(blank), error };
  }
  const checks = await Promise.all(
    rules.map(async (rule): Promise<RuleCheck> => {
      const run = runs.find((r) => r.name === checkName(rule));
      if (!run) return blank(rule);
      const base = { ...blank(rule), url: run.htmlUrl };
      if (run.status !== "completed") return { ...base, state: "pending" };
      if (run.conclusion === "success") return { ...base, state: "clear" };
      if (run.conclusion !== "failure") return { ...base, state: "inconclusive", conclusion: run.conclusion };
      const annotations = await repo.listCheckAnnotations(run.id).catch(() => []);
      return { ...base, state: "flagged", hits: annotations.map((a) => ({ rule: rule.id, path: a.path, line: a.line, match: a.message })) };
    }),
  );
  return { checks, error: null };
}
