// Site publishing orchestration: enable GitHub Pages (Actions build type), commit the workflow, remember the URL.
import type { Org } from "../../../generated/prisma/client";
import { prisma, now } from "../db.server";
import { BrainRepo } from "../github/repo.server";
import { SITE_PREP_PATH, SITE_WORKFLOW_PATH, pagesUrlFor, siteFiles, siteTitleFor } from "./site";
// Vite inlines the script source; the file itself is also what tests execute.
import prepScript from "./site-prep.mjs?raw";

export interface PublishResult {
  siteUrl: string;
  committed: boolean;
  warnings: string[];
}

const status = (e: unknown) => (e as { status?: number })?.status;

export async function publishSite(org: Org): Promise<PublishResult> {
  const repo = await BrainRepo.forOrg(org);
  if (!(await repo.headSha())) throw new Error("The brain repository is empty; scaffold it first.");
  const warnings: string[] = [];
  const wanted = siteFiles({ defaultBranch: repo.defaultBranch, siteTitle: siteTitleFor(org.name) }, prepScript);
  const writes: typeof wanted = [];
  for (const f of wanted) if ((await repo.readFile(f.path))?.content !== f.content) writes.push(f);

  let siteUrl = pagesUrlFor(repo.owner, repo.repo);
  try {
    siteUrl = await repo.enablePagesViaActions();
  } catch (e) {
    warnings.push(`GitHub Pages could not be enabled automatically (${(e as Error).message}). Enable it once by hand at ${repo.htmlUrl}/settings/pages with Source set to "GitHub Actions"; the workflow then deploys on its next run.`);
  }
  if (writes.length) {
    try {
      await repo.commit({ branch: repo.defaultBranch, message: "site: build with Quartz and publish to GitHub Pages\n\nGenerated by reedright. The site is a cache of this repository.", writes });
    } catch (e) {
      if (status(e) === 422 || status(e) === 403) {
        throw new Error(`GitHub refused the workflow file (${(e as Error).message}). The reedright GitHub App needs the "Workflows: read and write" permission: add it to the app, then accept the permission update on this installation.`);
      }
      throw e;
    }
  }
  await prisma().org.update({ where: { id: org.id }, data: { siteUrl, sitePublishedAt: org.sitePublishedAt ?? now() } });
  return { siteUrl, committed: writes.length > 0, warnings };
}

/** Trigger a build without a push (needs the Actions permission). */
export async function rebuildSite(org: Org): Promise<void> {
  const repo = await BrainRepo.forOrg(org);
  await repo.dispatchWorkflow(SITE_WORKFLOW_PATH.split("/").pop()!);
}

export async function unpublishSite(org: Org): Promise<{ removed: string[] }> {
  const repo = await BrainRepo.forOrg(org);
  const removed: string[] = [];
  for (const p of [SITE_WORKFLOW_PATH, SITE_PREP_PATH]) if (await repo.readFile(p)) removed.push(p);
  if (removed.length) await repo.commit({ branch: repo.defaultBranch, message: "site: stop publishing\n\nGenerated by reedright.", writes: [], deletes: removed });
  await prisma().org.update({ where: { id: org.id }, data: { siteUrl: null, sitePublishedAt: null } });
  return { removed };
}
