#!/usr/bin/env node
// Generated by reedright (https://reedright.info). Runs in GitHub Actions right before `quartz build`;
// nothing it changes is committed back. Usage: node site-prep.mjs <brain checkout> <quartz checkout>
// Environment: SITE_TITLE (home page and site title), BASE_URL (host + base path, no scheme; from configure-pages).
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const [brain = "brain", quartz = "quartz"] = process.argv.slice(2);
const siteTitle = process.env.SITE_TITLE || "Brain";
const baseUrl = (process.env.BASE_URL || "").replace(/^https?:\/\//, "").replace(/\/+$/, "");
const ENTRY_DIRS = ["rules", "procedures", "refs", "observations"];

// A JSON string is a valid YAML double-quoted scalar and a valid TypeScript string literal.
const quote = (s) => JSON.stringify(String(s));

function* markdownFiles(dir) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.name.startsWith(".") || e.name === "node_modules") continue;
    const p = join(dir, e.name);
    if (e.isDirectory()) yield* markdownFiles(p);
    else if (e.name.endsWith(".md")) yield p;
  }
}

function split(raw) {
  const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(raw);
  return m ? { fm: m[1].split(/\r?\n/), body: raw.slice(m[0].length) } : { fm: [], body: raw };
}

// 1. Every page gets a title (its first heading, which is then dropped from the body so it is not shown twice)
//    and tags for its type and domain, taken from the path. Existing keys are never overwritten.
let annotated = 0;
for (const file of markdownFiles(brain)) {
  const rel = relative(brain, file).split(sep).join("/");
  const { fm, body: original } = split(readFileSync(file, "utf8"));
  const has = (key) => fm.some((line) => new RegExp(`^${key}\\s*:`).test(line));
  const add = [];
  let body = original;
  if (!has("title")) {
    const h1 = /^#\s+(.+?)\s*$/m.exec(body);
    if (h1) body = body.replace(h1[0], "").replace(/^\n+/, "");
    add.push(`title: ${quote(h1 ? h1[1] : rel.replace(/\.md$/, "").split("/").pop())}`);
  }
  if (!has("tags")) {
    const seg = rel.split("/");
    const tags = [];
    if (seg[0] === "archive") {
      tags.push("archived");
      seg.shift();
    }
    if (ENTRY_DIRS.includes(seg[0]) && seg.length > 2) tags.push(seg[0], seg[1]);
    if (tags.length) add.push(`tags: [${tags.map(quote).join(", ")}]`);
  }
  if (!add.length) continue;
  writeFileSync(file, `---\n${[...fm, ...add].filter((line) => line.trim()).join("\n")}\n---\n\n${body}`);
  annotated++;
}

// 2. The home page is the manifest with every path turned into a link, unless the brain ships its own index.md.
const indexPath = join(brain, "index.md");
if (!existsSync(indexPath)) {
  const manifestPath = join(brain, "MANIFEST.md");
  const manifest = existsSync(manifestPath)
    ? readFileSync(manifestPath, "utf8")
        .replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, "")
        .replace(/^#\s+MANIFEST\s*\r?\n/, "")
        .replace(/^\| ((?:rules|procedures|refs|observations|archive)\/\S+\.md) \|/gm, (_m, p) => `| [${p}](${p}) |`)
    : "No MANIFEST.md yet.";
  writeFileSync(
    indexPath,
    `---\ntitle: ${quote(siteTitle)}\n---\n\nA browsable view of the brain, built from the repository by [reedright](https://reedright.info) with [Quartz](https://quartz.jzhao.xyz). The repository is the source of truth; this site is a cache of it.\n\n${manifest}`,
  );
}

// 3. Quartz configuration (Quartz 4.5.x). Change the look here; the workflow pins the Quartz version.
writeFileSync(
  join(quartz, "quartz.config.ts"),
  `import { QuartzConfig } from "./quartz/cfg"
import * as Plugin from "./quartz/plugins"

// Written by .github/reedright/site-prep.mjs on every build. Edit that script, not this file.
const config: QuartzConfig = {
  configuration: {
    pageTitle: ${quote(siteTitle)},
    pageTitleSuffix: "",
    enableSPA: true,
    enablePopovers: true,
    analytics: null,
    locale: "en-US",
    baseUrl: ${quote(baseUrl)},
    ignorePatterns: ["private", "templates", ".obsidian", ".github", "node_modules"],
    defaultDateType: "created",
    theme: {
      fontOrigin: "googleFonts",
      cdnCaching: true,
      typography: { header: "Schibsted Grotesk", body: "Source Sans Pro", code: "IBM Plex Mono" },
      colors: {
        lightMode: {
          light: "#faf8f8",
          lightgray: "#e5e5e5",
          gray: "#b8b8b8",
          darkgray: "#4e4e4e",
          dark: "#2b2b2b",
          secondary: "#284b63",
          tertiary: "#84a59d",
          highlight: "rgba(143, 159, 169, 0.15)",
          textHighlight: "#fff23688",
        },
        darkMode: {
          light: "#161618",
          lightgray: "#393639",
          gray: "#646464",
          darkgray: "#d4d4d4",
          dark: "#ebebec",
          secondary: "#7b97aa",
          tertiary: "#84a59d",
          highlight: "rgba(143, 159, 169, 0.15)",
          textHighlight: "#b3aa0288",
        },
      },
    },
  },
  plugins: {
    transformers: [
      Plugin.FrontMatter(),
      Plugin.CreatedModifiedDate({ priority: ["frontmatter", "git", "filesystem"] }),
      Plugin.SyntaxHighlighting({ theme: { light: "github-light", dark: "github-dark" }, keepBackground: false }),
      Plugin.ObsidianFlavoredMarkdown({ enableInHtmlEmbed: false }),
      Plugin.GitHubFlavoredMarkdown(),
      Plugin.TableOfContents(),
      Plugin.CrawlLinks({ markdownLinkResolution: "relative" }),
      Plugin.Description(),
      Plugin.Latex({ renderEngine: "katex" }),
    ],
    filters: [Plugin.RemoveDrafts()],
    emitters: [
      Plugin.AliasRedirects(),
      Plugin.ComponentResources(),
      Plugin.ContentPage(),
      Plugin.FolderPage(),
      Plugin.TagPage(),
      Plugin.ContentIndex({ enableSiteMap: true, enableRSS: true }),
      Plugin.Assets(),
      Plugin.Static(),
      Plugin.Favicon(),
      Plugin.NotFoundPage(),
    ],
  },
}

export default config
`,
);

console.log(`site-prep: ${annotated} pages annotated; home page ${existsSync(indexPath) ? "ready" : "missing"}; baseUrl ${baseUrl || "(unset)"}`);
