// Pure half of site publishing: the GitHub Actions workflow that builds a Quartz site from the brain and deploys
// it to GitHub Pages. The site is a cache of the repository (RFC §1); deleting the two generated files stops it.
export const SITE_WORKFLOW_PATH = ".github/workflows/reedright-site.yml";
export const SITE_PREP_PATH = ".github/reedright/site-prep.mjs";
export const QUARTZ_REF = "v4.5.2";

export const siteTitleFor = (orgName: string) => `${orgName} brain`;

/** Where GitHub Pages serves a repository by default (a custom domain replaces this once Pages reports it). */
export function pagesUrlFor(owner: string, repo: string): string {
  const o = owner.toLowerCase();
  return repo.toLowerCase() === `${o}.github.io` ? `https://${o}.github.io/` : `https://${o}.github.io/${repo}/`;
}

export function renderSiteWorkflow(input: { defaultBranch: string; siteTitle: string }): string {
  const title = JSON.stringify(input.siteTitle); // a JSON string is a valid YAML double-quoted scalar
  return `# Generated by reedright (https://reedright.info). Builds a browsable site of this brain with Quartz and publishes
# it to GitHub Pages on every push to ${input.defaultBranch}. The repository stays the source of truth; the site is a
# cache of it. Delete this file and .github/reedright/ to stop publishing.
name: reedright site

on:
  push:
    branches: [${input.defaultBranch}]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: reedright-site
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the brain
        uses: actions/checkout@v4
        with:
          path: brain
          fetch-depth: 0
      - name: Check out Quartz
        uses: actions/checkout@v4
        with:
          repository: jackyzha0/quartz
          ref: ${QUARTZ_REF}
          path: quartz
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: quartz/package-lock.json
      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install Quartz
        working-directory: quartz
        run: npm ci
      - name: Prepare content
        env:
          SITE_TITLE: ${title}
          BASE_URL: \${{ steps.pages.outputs.host }}\${{ steps.pages.outputs.base_path }}
        run: node brain/${SITE_PREP_PATH} brain quartz
      - name: Build the site
        working-directory: quartz
        run: npx quartz build -d ../brain -o public
      - name: Upload the site
        uses: actions/upload-pages-artifact@v3
        with:
          path: quartz/public
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
`;
}

/** The two files committed to the brain repository. `prepScript` is the source of site-prep.mjs. */
export function siteFiles(input: { defaultBranch: string; siteTitle: string }, prepScript: string): Array<{ path: string; content: string }> {
  return [
    { path: SITE_WORKFLOW_PATH, content: renderSiteWorkflow(input) },
    { path: SITE_PREP_PATH, content: prepScript },
  ];
}
